src/renderer/components/player/HeadlessScenePlayer.tsx, src/renderer/components/player/Player.tsx
Previously, overlay didn't work in the case that the scene loaded first
Now, if the scene finishes loading before the overlay, a overlay loading circle appears and then the slideshow starts once both scenes are loaded.
=> Fix overlay when scene loads first

src/renderer/components/player/HeadlessScenePlayer.tsx, src/renderer/components/player/ImagePlayer.tsx
So, running the animated-gif detection when we're initializing the URL list just takes too long and results in unmanageable load times for large sets.
Instead, running a check over gifs when the image source is loaded impacts performance much less and is hardly even noticed by the user. If the user selects a _very_ fast transition time, they may notice a slight delay... but on the order of milliseconds.
Cleaned up my code a little
=> Animated GIF Detection fix

package.json, src/declarations.d.ts, src/renderer/components/player/ImagePlayer.tsx, yarn.lock
So, since we could potentially use the duration of animated gifs, I found an alternative to `animated-gif-detector` which does both (and more... and faster! 👍): https://github.com/Prinzhorn/gif-info
I implemented gif-info and included a snippet to store the duration, though I'm not actually doing anything with that variable yet.
=> Use gif-info instead of animated-gif-detector

src/renderer/components/player/HeadlessScenePlayer.tsx, src/renderer/components/player/ImageContextMenu.tsx, src/renderer/components/player/ImagePlayer.tsx, src/renderer/components/player/ImageView.tsx, src/renderer/components/player/Player.tsx, src/renderer/components/sceneDetail/SceneDetail.tsx, src/renderer/style.scss
This PR addresses #42 
Added a ContextMenu object and customized specifically for image information
When right clicking an image in the player it will _always_ display a link to the image (which when clicked copies the link to the clipboard) and an "Open" option which opens the link.
If the link is to a file, it will also display "Show in Folder" and "Delete" options. "Delete" will confirm the user wants to delete the file before actually deleting.
`historyOffset` and `historyPaths` logic was fixed
=> Add ContextMenu with image information

src/renderer/Scene.tsx, src/renderer/components/player/HeadlessScenePlayer.tsx, src/renderer/components/player/ImagePlayer.tsx, src/renderer/components/sceneDetail/SceneDetail.tsx
This addresses #50 
Added a new option to scene which indicates if full gif animations should play. This only effects GIFs (obviously) and only changes the timing settings if timeout was _less_ than animation time for gif. E.g. If constant time is set to 5 seconds, any gifs that take longer than 5s to animate will extend timeout, otherwise, timeout will be 5s.
Because of the way images are processed, it is necessary to associate the currently displayed image with the timeout. Therefore, it was easiest to attach this data to the `Image` object itself. I co-opted the `alt` field for this purpose, but this data could be relocated later if necessary.
=> Add option to play full GIF animation

src/renderer/components/Meta.tsx, src/renderer/components/player/Player.tsx, src/renderer/components/sceneDetail/ControlGroup.tsx, src/renderer/components/sceneDetail/SceneDetail.tsx, src/renderer/style.scss
The first commit makes  some small improvements to the fullscreen functionality: 
* When entering full screen, the React Menu is also hidden. This is repopulated when fullscreen is exited
* Fullscreen is automatically exited when the "Back" button is pressed. This prevents users (who don't know the hotkey) from getting stuck in fullscreen.
The second commit addresses #46 .
* A sidebar is added to `Player` with a subset of options from `SceneDetail` (namely Timing and Effects). 
* For now, I just copied these elements from `SceneDetail` and implemented them the same.
* They need to be pulled out into their own `Component`s eventually.
* Verified that changes made while playing take effect and persist when user returns to `SceneDetail`.
=> Improve fullscreen & add SceneOption Sidebar

src/renderer/components/player/Player.tsx, src/renderer/components/sceneDetail/EffectGroup.tsx, src/renderer/components/sceneDetail/SceneDetail.tsx, src/renderer/components/sceneDetail/TimingGroup.tsx
This PR satisfies the outstanding requirements for #46. Timing and Effects controls have been moved into respective Components and are consistently applied to `SceneDetail` and `Player`.
Noticed that changing overlay scenes did not work as desired (they need to load and play at the same time it seems). This could be improved later. In the mean time, prevented overlay from being changed while playing (but opacity can be changed).
=> Move TimingGroup and EffectGroup into respective components

src/renderer/components/ui/Progress.tsx, src/renderer/style.scss
Fully centered, and we render a tiny bit of the circle even if no directories have loaded yet.
=> Fix visual appearance of loading indicator

src/renderer/components/player/ImagePlayer.tsx
`gifInfo` expects a path like "D:\rips\0ni-chan" but `new URL(url).pathname` returns "\D:\rips\0ni-chan". Just removed first character from `pathname`
=> GifInfo bugfix

.gitignore, Makefile
1) Can this be pulled into the master - or alternatively can 32bit Linux support be added to the Makefile and the .gitignore files?
2) I have tested and it works on 32 bit Linux (Debian 9 Stretch)  :)  
3) FlipFlip also works on the RaspberryPi 3 - the MakeFile would need to be altered to include the "arm7l" architecture. 
`electron-packager app FlipFlip ==platform=linux --arch=armv7l`
=> Adding support for 32bit Linux

src/renderer/components/player/Player.tsx, src/renderer/style.scss
This is a very trivial change to the Style.css and the Player.tsx  - essentially this slides the sidebar in only when the mouse approaches the left side of the Player window.
=> Slide Sidebar in

src/renderer/components/player/ImagePlayer.tsx
reference: https://github.com/ififfy/flipflip/issues/78 
Created:   ImagePlayer.state.nextImageID=0
Incremented: ImagePlayer  render() method 
Used in the key:  key={this.state.nextImageID.toString()
not sure if this is exactly the way you wanted it doing - it works on my testing.
=> Fix to Cross-fade bug #78

src/renderer/style.scss
Added local("Liberation Sans"), local("FreeSans") to the @font-face rule in styles.sccs
This resolves issue https://github.com/ififfy/flipflip/issues/83 tested on Debian 9 Linux.
Thanks @ififfy  for the direction.
=> Add standard fonts

src/renderer/components/player/Player.tsx
These are a few quick enhancements to the Player's MenuBar for your consideration:
1. Support the Player staying on top (which is particularly useful if in windowed mode);
2. Support explicit hiding and showing of the MenuBar.
=> Menu Enhancements to support Player 'AlwaysOnTop' and Show/Hide of Menu

src/renderer/components/Meta.tsx
https://github.com/ififfy/flipflip/issues/98#issuecomment-462073246 
The version number from package.json is now embedded in the data.json file.
**in passing I note the package.json file has not been updated to 2.0.0 yet**  
so the internal version number of flipflip is still 1.2.0.
=> Version Numbers in data.json

src/renderer/components/Meta.tsx, src/renderer/components/ScenePicker.tsx, webpack.dev.js, webpack.prod.js
This update to version numbering works by creating a global compile-time variable and thus also works in a debug environment.
Having committed - I'm wondering if rather than calling the variable "VERSION"  I should have perhaps called it ``__VERSION__``  to distinguish that this is a compile-time variable.
Let me know if you would like me to change it to ``__VERSION__`` before committing...
F3
=> Making Version Number work in debug environment

src/renderer/components/Meta.tsx, webpack.dev.js, webpack.prod.js
- Compile-time global variable `VERSION` has been renamed to `__VERSION__` 
- On the first time v2.0.0 encounters an unversioned data.json configuration file - an attempt is made to upgrade it to v2.0.0
- The existing data.json file is archived in the .config folder by renaming to append an epoch time
- The new v.2.0.0 data.json file is initialized and any directories in existing scenes are hacked into the  sources of the Library ... taking care to de-duplicate entries
- Should upgrading the data.json file fail during the upgrade - then all things being equal the previous data.json file will have been archived - so it can be recovered or investigated etc. and a restart should self-heal and create a virgin v2.0.0 data.json file.
- Hydrating the Scenes needs to be done - similarly to the …
=> Hydrate v2.0.0 Library from v1.2.0 Scenes

src/renderer/style.scss
Quick bug fix via `style.scss`
The editable area of the Scene Name in Scene Details was dynamic - so that when\if a user deleted the name and saved it the area was reduced to a width and height of 0 x 0.
I am not sure if these suggested values are acceptable i.e. 10rem ad 2 rem - so they can be changed to suit.
F3
=> Bug Fix: Enabling Scene Name to be edited (after deletion)

Readme_vscode.md
This is a TL;DR Readme explaining the quickest way to configure remote debugging of Flipflip using Visual Studio Code.
The initial PR went up in smoke when I was faffing with git branches - to try and do a separate PR for Fonts.
F3
=> FlipFlip remote debugging configuration for Visual Studio Code

src/renderer/components/Meta.tsx, src/renderer/components/library/TagManager.tsx, src/renderer/components/sceneDetail/SourcePicker.tsx, src/renderer/style.scss
This PR addresses #104 & #105 
The current tag ordering is haphazard and can look confusing. Instead, just order them all by the order in `TagManager` . Also, delete/rename a tag from sources if it is deleted/renamed from `TagManager`.
Any issues? 🙂
=> Remove manual tag sorting, Order/Update/Remove source tags to match TagManager

src/renderer/components/Meta.tsx, src/renderer/components/config/BackupGroup.tsx, src/renderer/components/config/ConfigForm.tsx, src/renderer/components/ui/Progress.tsx, src/renderer/style.scss, src/renderer/utils.ts
This is some starting work for Backup/Restore functionality (#132) . Currently, this is very simplistic, so I'd love some input about how this should ultimately work for users.
Currently (from `Config`):
* User hits "Backup Data"
* FlipFlip creates a timestamped archive file
* FlipFlip creates (or overrides) the file "data - Backup.json"
* User hits "Restore Last Backup" (only enabled if "data - Backup.json" exists)
* Sets `Meta` state to contents of "data - Backup.json"
The above process just leaves a bunch of archive files, while overriding the backup. I think it'd be better to at least (1) use the most recent archive file or (2) provide a list of versions to restore from.
But I wasn't sure if it made sense for a user to want to restore an older backup. The only reason I could think …
=> Allow Backup/Restore

Readme_vscode.md, webpack.dev.js
The `webpack.dev.js` file needed updating to ensure that when remote debugging the source mappings worked properly,
=> Remote debugging - update to ensure source mappings work properly

src/renderer/Config.tsx, src/renderer/components/player/Player.tsx, src/renderer/icons/fullscreen.svg, src/renderer/style.scss
This PR is an attempt to persist the alwaysOnTop and menuBarVisibility states between launches of Flipflip,   In addition it also deals with activating the menu when the menu has been hidden see #129.  It does this by toggling the menu when the mouse enters the `u-button-row`
I say 'attempt' - because I am not sure if you will approve of using the Config class for storing the states, and the toggling of the menu on entry to the u-button-row is a clunky.
F3
=> Persisting alwaysOnTop and  menuBarVisibility

src/renderer/components/Meta.tsx, src/renderer/components/ScenePicker.tsx, src/renderer/components/config/BackupGroup.tsx, src/renderer/data/AppStorage.tsx, src/renderer/data/actions.ts
`Meta.tsx` was way too big, and it’s bad practice to have logic in view files.
I changed every method in `Meta.tsx` to be a function that takes a state object and returns a `setState()` argument. This means most of the functions are pure and testable, and we can split the file up so it’s easier to find things.
**Because this touches every function in the entire app, I need time to test it.**
=> Factor all logic out of Meta.tsx into data/actions.ts [UNTESTED]

.vscode/launch.json, Readme_vscode.md, src/main/WindowManager.ts, src/main/main.ts
I noticed you went to a lot of trouble to include debugger instructions. That's awesome! I made it a little bit easier by adding a `--no-dev-tools` command line option that prevents the opening of the Chrome dev tools, and adding that flag to `launch.json`. At that point it seemed safe to just include `launch.json` in the repo. I know it doesn't work on Windows, but better to serve more than zero people than all the people!
=> Include vscode debugging config in repo

src/renderer/components/Meta.tsx
When starting FlipFlip with the last viewed scene being a library temp scene, getLibrarySource will return null. This causes an error that FlipFlip does not recover from, when it attempts to access null.tags.
Making this access null conditional resolves this entirely.
=> Fix potential nullref error causing lockup on load

src/renderer/components/player/SourceScraper.tsx, src/renderer/data/utils.ts
A basic quality of life update to account for the fact that FlipFlip appends `/rss` to the end of bdsmlr urls, which makes urls like `https://somecoolblog.bdsmlr.com/` and `https://somecoolblog.bdsmlr.com/rss` not work. 
Wasn't quite sure where the logic for this should live, so definitely open to feedback if it should be elsewhere. Mostly I was having fun getting set up and poking around the code base, but feel free to use if it's helpful!
=> QOL Updates for bdsmlr URLs

src/renderer/components/configGroups/SceneOptionCard.tsx, src/renderer/components/player/Scrapers.ts, src/renderer/index.html
This is a rebased version of #265
> Issue: When playing a Scene from certain sources, gif images from that source don't have the Scene's "GIF Options" selection applied to them. So, for instance, if the Scene's timing is a Constant 1000ms and the Scene's "GIF Options" is set to "Play Full", gifs from the affected sources will always only play for 1000ms, regardless of their actual duration. (Reported in Issue #266 )
>
>Technical background:
This issue affects all sources who's file URLs do not include an extension in the URL - namely, all sources where the file URLs are actually an API request. I found it when testing other things for a Hydrus source, from which FlipFlip gather's file URLs that look like this:
http://localhost:45869/get_files/file?file_id=4674&Hydrus-Client-API-Access-Key= …
=> Allow Gif Option to respect Hydrus sources

src/renderer/components/player/Scrapers.ts
This is a rebased version of #264
> This one's pretty straightforward - rather than use a regex to get the tags, we just use the Hydrus URL configured in the source directly. Since there's already a check to make sure that the source URL starts with the URL preserved in the Hydrus auth, we can be confident that it's a Hydrus URL either way.
>
> This will allow Hydrus sources configured with the system_inbox or system_archive query parameters to respect those parameters (as mentioned in issue #262 ), as well as make room for future query parameters the Hydrus dev may add to that endpoint over time.
=> Issue #262 - Preserve Additional Query Params When Using Hydrus URL Source
